export const SCAN_DURATION_MS = 4000
export const DETECTION_HITS_REQUIRED = 5
export const DETECTION_MISSES_TO_RESET = 15
export const DETECTION_INTERVAL_MS = 30
export const DETECTION_SCORE_THRESHOLD = 0.4
export const DETECTION_INPUT_SIZE = 320
